# Generated by Django 3.0.1 on 2019-12-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='thumb',
            field=models.ImageField(blank=True, default='Logo-Default.png', upload_to=''),
        ),
    ]
