# Generated by Django 3.0.1 on 2019-12-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_artigo_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='thumb',
            field=models.ImageField(blank=True, default='logo-default.png', upload_to=''),
        ),
    ]
